languageCode = "es"
languageName = "Español"
languageDirection = "ltr"
weight = 2

title = "ignacio.uk"
copyright = "© 2024, bajo CC BY-NC-SA 4.0"

[params]
  dateFormat = "January 2, 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "ignacio"
  image = "img/author.jpg"
  headline = "22, Chile :pushpin: A veces escribo, y pocas con sentido"
  bio = "A veces escribo, y pocas con sentido"
  links = [
    { email = "mailto:hola@ignacio.lol" },
    { github = "https://github.com/ignaciocastro" },
    { lastfm = "https://lastfm.com/user/ignaciocm" },
    { x-twitter = "https://twitter.com/ignaseeo" },
  ]
