backend:
  name: github
  repo: ignaciocastro/ignacio.uk
  branch: main
  base_url: https://sveltia-cms-auth.ignacio.workers.dev/

media_folder: "assets/img"
public_folder: "/img"

i18n:
  locales: [en, es]
  default_locale: en

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
    filename: "{{slug}}/index.{{locale}}.md"
    editor:
      preview: false