backend:
  name: github
  repo: ignaciocastro/ignacio.uk
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://sveltia-cms-auth.ignacio.workers.dev/

media_folder: "assets/img" # Folder where images will be uploaded
public_folder: "/img" # Folder where images will be accessed

i18n:
  structure: multiple_folders
  locales: 
    - en
    - es

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "english-posts"
    label: "English Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}/index.en"
    extension: "md"
    filter:
      field: "lang"
      value: "en"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Language"
        name: "lang"
        widget: "hidden"
        default: "en"

  - name: "spanish-posts"
    label: "Spanish Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}/index.es"
    extension: "md"
    filter:
      field: "lang"
      value: "es"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Language"
        name: "lang"
        widget: "hidden"
        default: "es"