backend:
  name: github
  repo: ignaciocastro/ignacio.uk
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://sveltia-cms-auth.ignacio.workers.dev/

media_folder: "assets/img" # Folder where images will be uploaded
public_folder: "/img" # Folder where images will be accessed

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{slug}}"
    path: "{{year}}-{{slug}}/index.{{locale}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Language", name: "locale", widget: "select", options: ["en", "es"], default: "en" }
      - { label: "Body", name: "body", widget: "markdown" }
    i18n:
      structure: multiple_files
      locales: ["en", "es"]
      default_locale: "en"