backend:
  name: github
  repo: ignaciocastro/ignacio.uk # Your GitHub repository
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://sveltia-cms-auth.ignacio.workers.dev/ # Custom authentication URL

media_folder: "assets/img" # Folder where images will be uploaded
public_folder: "/img" # Folder where images will be accessed

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    media_folder: ''
    public_folder: ''
    path: "{{slug}}/index.{{language}}.md"
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
    i18n:
      structure: multiple_folders
      locales: [en, es]
      default_locale: en

i18n:
  structure: multiple_folders
  locales: [en, es]