backend:
  name: github
  repo: ignaciocastro/ignacio.uk
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://sveltia-cms-auth.ignacio.workers.dev/

media_folder: "assets/img" # Folder where images will be uploaded
public_folder: "/img" # Folder where images will be accessed

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Show Summary", name: "showSummary", widget: "boolean", default: true}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
    i18n: true
    nested:
      depth: 1
      summary: '{{title}}'
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    format: 'toml-frontmatter'