backend:
  name: github
  repo: ignaciocastro/ignacio.uk # Your GitHub repository
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://sveltia-cms-auth.ignacio.workers.dev/ # Custom authentication URL

media_folder: "assets/img" # Folder where images will be uploaded
public_folder: "/img" # Folder where images will be accessed

i18n:
  structure: multiple_files # Multiple language versions of the same content in the same folder
  default_language: en
  locales:
    - { code: en, label: "English" }
    - { code: es, label: "Español" }

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Language", name: "language", widget: "select", options: ["en", "es"], default: "en" }
    i18n:
      structure: multiple_files # Using the same folder with language codes in filenames
      locales:
        - { code: en, label: "English" }
        - { code: es, label: "Español" }
    path: "{{slug}}/index.{{language}}.md" # Post file path based on language